language: ruby
rvm:
- 2.3.1
install:
- bundle install
- bundle exec jekyll build
script:
- bundle exec jekyll build --trace
- bundle exec htmlproofer ./_site --only-4xx --allow-hash-href
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
